# Sponsorship and Support

# If you'd like to support this project and help keep these materials
# free and up-to-date, consider:

# ☕ Buying me a coffee
# ko_fi: patrickwiloak

# 🎥 Subscribing to YouTube
custom: ['https://youtube.com/@patrickwiloak', 'https://patrickwiloak.com']
